development:
  adapter: mysql
  database: risk_development
  username: root
  password:
  host: localhost
  
test:
  adapter: mysql
  database: risk_testing
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: risk_production
  username: root
  password: 
  host: localhost

